############################应用基本配置################################
#spring:
#  application:
#    name:
#  http:
#    encoding:
#      enabled: true
#      charset: utf-8
#      force: true
##  main:
#    allow-bean-definition-overriding: true
#  shardingsphere:
#    datasource:
#      names: m1
#      m1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://119.23.138.15:3306/xpdemo?allowMultiQueries=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#        username: xpdemo
#        password: XiongP528454!
#    sharding:
#      tables:
#        user:
#          actualDataNodes: m1.user_$->{0..3}
#          tableStrategy:
#            inline:
#              shardingColumn: id
#              algorithmExpression: user_${(id >> 22) % 4}
#          keyGenerator:
#            type: SNOWFLAKE
#            column: id
#    props:
#      sql:
#        show: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
swagger:
  enable: true
logging:
  level:
    root: error
    org.springframework.web: error
    #    com.itheima.dbsharding: error
    druid.sql: debug
xxl:
  job:
    admin:
      addresses: http://192.168.8.246:8081/xxl-job-admin
    accessToken:
    executor:
      appname: xxl-job-test
      address:
      ip:
      port: 9918
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
########################### 数据库连接池配置##################################
spring:
  datasource:
    # mysql 连接配置
    host: 192.168.8.189
    username: richinfo_csp
    password: qvjjgGRuc5,i!@#
    #url: jdbc:mysql://${spring.datasource.host}/andFinance?allowMultiQueries=true&characterEncoding=UTF8&autoReconnect=true
    url: jdbc:mysql://${spring.datasource.host}/xp_demo?allowMultiQueries=true&characterEncoding=UTF8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接数大小/最小/最大
    initialSize: 5
    minIdle: 10
    maxActive: 30
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 1)Destroy线程检测连接的间隔时间(毫秒),当空闲时间大于minEvictableIdleTimeMillis时,关闭连接
    # 2)testWhileIdle申请连接时的执行检测条件:如果空闲时间大于此值,则执行validationQuery检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000
    # 配置连接保持空闲而不被关闭的最长时间(毫秒)
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 缓存PSCache开关(mysql建议关闭),并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    #maxPoolPreparedStatementPerConnectionSize: 100
    # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  jackson:
    default-property-inclusion: non_null
  #  rabbitmq:
  #    host: 192.168.8.186
  #    port: 5672
  #    username: xiong
  #    password: 123456
  #    ### 消息发送到交换机确认机制，是否返回回调
  #    publisher-returns: true
  #    ### 确认消息已发送到交换机，选择确认类型为交互
  #    publisher-confirm-type: correlated
  redis:
    host: 192.168.8.169
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
################################ mybatis-plus配置 ##################################
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ${src.base-package}.orm.model


  ################################ sharding-jdbc分库分表设置 ##################################

  #spring:
  #  shardingsphere:
  #    datasource:
  #      names: master
  #      master:
  #        type: com.alibaba.druid.pool.DruidDataSource
  #        driver-class-name: com.mysql.cj.jdbc.Driver
  #        username: xpdemo
  #        password: XiongP528454!
  #        url: jdbc:mysql://119.23.138.15:3306/xpdemo?characterEncoding=utf-8
  #    sharding:
  #      tables:
  #        user:
  #          actual-data-nodes: master.user_${0..3}
  #          table-strategy:
  #            inline:
  #              sharding-column: id
  #              algorithm-expression:  user_${id % 4}







  ############################ 日志输出配置 ##############


  #swagger:
  #  enable: true
  # 应用名称
#  servlet:
#logging:
#  level:
#    cn.richinfo.cspapi: trace
mica:
  xss:
    enabled: true
#    path-patterns: /user-info/**
#    context-path: /mall